# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-01 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='user_id',
            new_name='user',
        ),
    ]
