# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-29 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='serialised_code_rnd_tau_gam',
            new_name='serialised_code_rnd_tau_gam_R_att',
        ),
    ]
