# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20160729_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='expirydate',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
