# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-09 13:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20160701_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='value_of_coin',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator('0')]),
        ),
    ]
