# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_coins_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='value_of_coin',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (10, '10'), (15, '15'), (20, '20')]),
        ),
    ]
