# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_auto_20160630_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default='/static/merchant/images/no-img.jpg', upload_to='static/merchant/images/'),
        ),
    ]
