# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20160627_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=12),
        ),
    ]
