# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20160726_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublespendingz1touser',
            name='expirydate',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doublespendingz1touser',
            name='value_of_coin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
