# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20160628_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment', models.TextField()),
                ('jsonstring', models.TextField()),
            ],
        ),
    ]
