# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-19 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_coinvalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator('1')]),
        ),
    ]
