# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20160719_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinvalidation',
            name='num_of_coins',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinvalidation',
            name='user',
            field=models.TextField(default='ihp'),
            preserve_default=False,
        ),
    ]
