# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20160719_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleSpendingCoinHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.TextField()),
                ('serialised_entry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoubleSpendingz1Touser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z1', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
