# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-19 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_doublespendingcoinhistory_doublespendingz1touser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinvalidation',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='doublespendingz1touser',
            old_name='user',
            new_name='username',
        ),
    ]
